### ISSUE TITLE
Add Fyne interface version

### ISSUE THREAD

**Issue by andydotxyz** [HFO4/gameboy.live#12]
Congratulations on the project. I played around with it and pulled together an alternative Fyne based user interface https://github.com/andydotxyz/fynegameboy.

Before I worked to make a PR to include it here I thought I would check if that is interesting or not.

**Comment by HFO4** [comment]
Great works! It would be great to include this option!

**Comment by andydotxyz** [comment]
Great. Would you like to have a Fyne UI as an option (like the current GUI mode) as a build tag (to make an optional replacement for the current gui) or to replace the pixelgl implementation (which I think does not support scaling?).

**Comment by HFO4** [comment]
I think make it as an option is a good choice. If it works well, maybe we can change the default GUI to Fyne UI.
