### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by GeorgeMing** [HFO4/gameboy.live#29]
my go version 1.11.11

go build -o gbdotlive main.go

# github.com/go-gl/glfw/v3.2/glfw
In file included from ../github.com/go-gl/glfw/v3.2/glfw/c_glfw_linbsd.go:24:0:
../github.com/go-gl/glfw/v3.2/glfw/glfw/src/linux_joystick.c: In function ‘_glfwInitJoysticksLinux’:
../github.com/go-gl/glfw/v3.2/glfw/glfw/src/linux_joystick.c:224:42: warning: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 9 [-Wformat-truncation=]
             snprintf(path, sizeof(path), "%s/%s", dirname, entry->d_name);
                                          ^~~~~~~
In file included from /usr/include/stdio.h:862:0,
                 from /usr/include/X11/Xcursor/Xcursor.h:26,
                 from ../github.com/go-gl/glfw/v3.2/glfw/glfw/src/x11_platform.h:39,
                 from ../github.com/go-gl/glfw/v3.2/glfw/glfw/src/internal.h:169,
                 from ../github.com/go-gl/glfw/v3.2/glfw/glfw/src/x11_init.c:28,
                 from ../github.com/go-gl/glfw/v3.2/glfw/c_glfw_linbsd.go:19:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 12 and 267 bytes into a destination of size 20
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw
In file included from ../fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/c_glfw_linbsd.go:24:0:
../fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/glfw/src/linux_joystick.c: In function ‘_glfwInitJoysticksLinux’:
../fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/glfw/src/linux_joystick.c:224:42: warning: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 9 [-Wformat-truncation=]
             snprintf(path, sizeof(path), "%s/%s", dirname, entry->d_name);
                                          ^~~~~~~
In file included from /usr/include/stdio.h:862:0,
                 from /usr/include/X11/Xcursor/Xcursor.h:26,
                 from ../fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/glfw/src/x11_platform.h:39,
                 from ../fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/glfw/src/internal.h:169,
                 from ../fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/glfw/src/x11_init.c:28,
                 from ../fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/c_glfw_linbsd.go:19:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 12 and 267 bytes into a destination of size 20
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# github.com/HFO4/gbc-in-cloud/server
../github.com/HFO4/gbc-in-cloud/server/player.go:51:4: cannot use Driver (type *"github.com/HFO4/gbc-in-cloud/driver".ASCII) as type "github.com/HFO4/gbc-in-cloud/driver".DisplayDriver in field value:
        *"github.com/HFO4/gbc-in-cloud/driver".ASCII does not implement "github.com/HFO4/gbc-in-cloud/driver".DisplayDriver (wrong type for Run method)
                have Run(chan bool)
                want Run(chan bool, func())
../github.com/HFO4/gbc-in-cloud/server/player.go:289:38: not enough arguments in call to player.Emulator.DisplayDriver.Run
        have (chan bool)
        want (chan bool, func())

**Comment by codenoid** [comment]
yup

```
# github.com/HFO4/gbc-in-cloud/server
server/player.go:51:4: cannot use Driver (type *"github.com/HFO4/gbc-in-cloud/driver".ASCII) as type "github.com/HFO4/gbc-in-cloud/driver".D
isplayDriver in field value:
        *"github.com/HFO4/gbc-in-cloud/driver".ASCII does not implement "github.com/HFO4/gbc-in-cloud/driver".DisplayDriver (wrong type for 
Run method)
                have Run(chan bool)
                want Run(chan bool, func())
server/player.go:289:38: not enough arguments in call to player.Emulator.DisplayDriver.Run
        have (chan bool)
        want (chan bool, func())
```

**Comment by HFO4** [comment]
Strange 🤔 ,I'll take l look later.
