### ISSUE TITLE
Greetings!

### ISSUE THREAD

**Issue by tilkinsc** [HFO4/gameboy.live#3]
This is a very well put together project. Could you list more about the project, your motives, etc on the readme?

I am currently creating a gameboy emulator written in C++. I am also writing an assembler (with uniquely named opcodes) which in its core targets specifically the gb.

Here are some easy resources I have found for quick lookup of ops:
http://www.pastraiser.com/cpu/gameboy/gameboy_opcodes.html
http://imrannazar.com/Gameboy-Z80-Opcode-Map

In my assembler, I have switched LD (HL), * to SV (HL), * and some other changes that make sense. Like ADD A, * is just ADD *. I am interested in where you are leading this project and how you are going to implement state saving. For example, are you just going to dump a rom's-worth of memory or just the changes to the memory... are you going to make it modular in the sense you can serialize data structures and just reimport them?

I want my assembler to be able to export standard roms (and mine generated matches that of the standard bin) into source.

**Comment by HFO4** [comment]
Hi,

As English is not my native language, it might be difficult for me to express what I mean clearly.

I'm working on this project mostly fo fun and learning purpose. This [tutorial](http://www.codeslinger.co.uk/pages/projects/gameboy/beginning.html) inspired me a lot, so the idea of my emulation is similar to that tutorial. Modules in my emulator is close to reality. For example, CPU is just a struct union with variables to store registers and flags, Memory is just an array, of which first 32KBytes are copied from the game's ROM.

**Comment by tilkinsc** [comment]
If you want me to proof read, I can contribute. I am a native English speaker.

**Comment by HFO4** [comment]
> If you want me to proof read, I can contribute. I am a native English speaker.

That would be great!
