### ISSUE TITLE
Telnet server is down?

### ISSUE THREAD

**Issue by jruivo-dev** [HFO4/gameboy.live#4]
Hey, great project :)

I was trying to connect to `telnet gameboy.live 1989`, yet all I'm getting is `Trying 47.74.183.161...`
Is the server down?

I'm not sure if that's even an actual server 😅  or if we're supposed to host our own server first.

**Comment by HFO4** [comment]
The telnet server is up now, and the ip address you've given is correct. I'm not sure what the problem is actually...

The demo server is located in Singapore, maybe the route is unreachable in somewhere.

**Comment by jruivo-dev** [comment]
Dang, must be some restrictions here at my office then.
I'll try it out later at home.

**Comment by jruivo-dev** [comment]
Tried it at home, works perfectly fine! Cheers
