### ISSUE TITLE
server/server.go:44:12: assignment mismatch: 1 variable but uuid.NewV4 returns 2 values

### ISSUE THREAD

**Issue by halleyshx** [HFO4/gameboy.live#9]
go build -o gbdotlive main.go
\# github.com/HFO4/gbc-in-cloud/server
server/server.go:44:12: assignment mismatch: 1 variable but uuid.NewV4 returns 2 values

in the server/server.go
PlayerID := uuid.NewV4()
I change the return like this:
PlayerID, _ := uuid.NewV4()
It worked.

**Comment by HFO4** [comment]
Thanks for reporting!

**Comment by halleyshx** [comment]
> Thanks for reporting!

No thanks,:blush:

**Comment by jdgiotta** [comment]
What version of golang was this not working for?

**Comment by jmahc** [comment]
I am on 1.12.5 and had to **revert** the change because I was getting

`assignment mismatch: 2 variables but uuid.NewV4 returns 1 value`

**Comment by shokinn** [comment]
@HFO4 
Did you take a look on this?
I've the same issue as @jmahc.

I'm on a Alpine 3.9 with a GO 1.12.5 and building it from the master branch.

**Comment by HFO4** [comment]
@shokinn @jmahc 
I‘ve already revert the previous commit, apology for not testing this!

@halleyshx 
Try to build with go version above 1.11?

**Comment by halleyshx** [comment]
@HFO4  Sorry,I forgot. Maybe it was go1.12.4
